# Generated by Django 3.1.4 on 2020-12-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20201216_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='main_image',
            field=models.ImageField(upload_to='static'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='water_mark',
            field=models.ImageField(upload_to='static'),
        ),
    ]
