# Generated by Django 3.1.4 on 2020-12-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20201216_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='main_image',
            field=models.ImageField(upload_to='_static'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='water_mark',
            field=models.ImageField(upload_to='_static'),
        ),
    ]
