# Generated by Django 3.1.4 on 2020-12-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20201216_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='merged_image',
            field=models.ImageField(upload_to='_static'),
        ),
    ]
